name: generate asci artwork

on: push

jobs:
    runs_job:
        runs-on: ubuntu-latest
        steps:
            - name: install cowsay
              uses: sudo apt-get install cowsay -y
                  
            - name: exec cmd 
              run: cowsay -f dragon "run for " >> dragon.txt

            - name: sleep for 30 sec
              run: sleep 30
    test_job:
        runs-on: ubuntu-latest
        steps:
            - name: slepp for 10 sec
              run: sleep 10

            - name: test file
              run: grep -i "run" dragon.txt
    deploy_job:
        runs-on: ubuntu-latest
        steps:
            - name: Read file
              run: cat dragon.txt

            - name: Deploy
              run: echo Deploying....
            
              

 
            