name: generate asci artwork

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout Repo
              uses: actions/checkout@v4
                    
            - name: install cowsay
              run: sudo apt-get install cowsay -y

            - name: exec
              run: cowsay -f dragon "run for " >> dragon.txt

            - name: test
              run: grep -i "dragon" dragon.txt

            - name: Read files
              run: cat dragon.txt

            - name: list repo files 
              run: ls -ltra
