name: filter
on:
    workflow_dispatch: 
            # schedule:
    #     - cron: '*/59 * * * *'
    push: 
        # branches-ignore: 
        #     - feature/*
        #     - test/**
        branches: 
            - main
            - '!feature/*'

    pull_request: 
        types: 
            - opened
            - closed
        paths-ignore: 
            - README.rm
        branches: 
            - main
jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
            - name: hi
              run: echo this exec - ${{github.event_name}}


